# Generated by Django 5.1.15 on 2026-09-19 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("job_title", models.CharField(db_index=True, max_length=120)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Engineering", "Engineering"),
                            ("Sales", "Sales"),
                            ("Marketing", "Marketing"),
                            ("Finance", "Finance"),
                            ("HR", "HR"),
                            ("Operations", "Operations"),
                            ("Support", "Support"),
                            ("Legal", "Legal"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("L1", "L1"),
                            ("L2", "L2"),
                            ("L3", "L3"),
                            ("L4", "L4"),
                            ("L5", "L5"),
                            ("L6", "L6"),
                        ],
                        db_index=True,
                        max_length=4,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("F", "F"), ("M", "M"), ("X", "X")], max_length=1
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("US", "US"),
                            ("GB", "GB"),
                            ("DE", "DE"),
                            ("FR", "FR"),
                            ("IN", "IN"),
                            ("CA", "CA"),
                            ("AU", "AU"),
                            ("SG", "SG"),
                            ("BR", "BR"),
                            ("JP", "JP"),
                        ],
                        db_index=True,
                        max_length=2,
                    ),
                ),
                ("hire_date", models.DateField()),
                ("salary", models.PositiveIntegerField()),
                ("currency", models.CharField(editable=False, max_length=3)),
                (
                    "salary_usd",
                    models.PositiveIntegerField(db_index=True, editable=False),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="SalaryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("effective_date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=120)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_history",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "-id"],
            },
        ),
    ]
